/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gabri
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form TestejFrame
     */
    public CadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        toppane = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        midpane = new javax.swing.JPanel();
        jLId = new javax.swing.JLabel();
        jTPId = new javax.swing.JTextPane();
        jButtonBuscar = new javax.swing.JButton();
        jLDataNascimento = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jComboBStatus = new javax.swing.JComboBox<>();
        jLNome = new javax.swing.JLabel();
        jTPIncscricaoEstadual = new javax.swing.JTextPane();
        jLInscricaoEstadual = new javax.swing.JLabel();
        jTPCNPJ = new javax.swing.JTextPane();
        jLRazaoSocial = new javax.swing.JLabel();
        jTPRazaoSocial = new javax.swing.JTextPane();
        jLFone1 = new javax.swing.JLabel();
        jFTFFone1 = new javax.swing.JFormattedTextField();
        jLEmail = new javax.swing.JLabel();
        jTPEmail = new javax.swing.JTextPane();
        jLFone2 = new javax.swing.JLabel();
        jFTFFone2 = new javax.swing.JFormattedTextField();
        jLCep = new javax.swing.JLabel();
        jTPCep = new javax.swing.JTextPane();
        jButtonBuscarcep = new javax.swing.JButton();
        jButtonAddCEP = new javax.swing.JButton();
        jLComplemento = new javax.swing.JLabel();
        jTPComplemento = new javax.swing.JTextPane();
        jLRua = new javax.swing.JLabel();
        jTPRua = new javax.swing.JTextPane();
        jLBairro = new javax.swing.JLabel();
        jTPBairro = new javax.swing.JTextPane();
        jLCidade = new javax.swing.JLabel();
        jTPCidade = new javax.swing.JTextPane();
        jLEstado = new javax.swing.JLabel();
        jTPEstado = new javax.swing.JTextPane();
        jTPName = new javax.swing.JTextPane();
        bottompane = new javax.swing.JPanel();
        jButtonNew = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonExclui = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fomulário de Teste da GABISZOKA");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1280, 832));
        setName("cadastro"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 832));
        setSize(new java.awt.Dimension(1280, 832));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        toppane.setBackground(new java.awt.Color(109, 217, 108));
        toppane.setPreferredSize(new java.awt.Dimension(1280, 99));

        jLTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(242, 241, 243));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Cadastro Fornecedor");
        jLTitulo.setToolTipText("");
        jLTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jBExit.setBackground(new java.awt.Color(109, 217, 108));
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-voltar-48.png"))); // NOI18N
        jBExit.setBorderPainted(false);
        jBExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppaneLayout = new javax.swing.GroupLayout(toppane);
        toppane.setLayout(toppaneLayout);
        toppaneLayout.setHorizontalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppaneLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppaneLayout.setVerticalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitulo)
                    .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        midpane.setBackground(new java.awt.Color(255, 255, 255));
        midpane.setPreferredSize(new java.awt.Dimension(1280, 152));

        jLId.setBackground(new java.awt.Color(30, 30, 30));
        jLId.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLId.setForeground(java.awt.Color.gray);
        jLId.setText("ID");

        jTPId.setBackground(new java.awt.Color(229, 229, 229));
        jTPId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPId.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPId.setForeground(new java.awt.Color(0, 0, 0));

        jButtonBuscar.setBackground(new java.awt.Color(229, 229, 229));
        jButtonBuscar.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jButtonBuscar.setForeground(java.awt.Color.gray);
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-pesquisar-24.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setHideActionText(true);
        jButtonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonBuscar.setIconTextGap(30);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLDataNascimento.setBackground(new java.awt.Color(30, 30, 30));
        jLDataNascimento.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLDataNascimento.setForeground(java.awt.Color.gray);
        jLDataNascimento.setText("CNPJ");

        jLStatus.setBackground(new java.awt.Color(30, 30, 30));
        jLStatus.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLStatus.setForeground(java.awt.Color.gray);
        jLStatus.setText("Status");

        jComboBStatus.setBackground(new java.awt.Color(229, 229, 229));
        jComboBStatus.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jComboBStatus.setForeground(java.awt.Color.gray);
        jComboBStatus.setMaximumRowCount(2);
        jComboBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jComboBStatus.setSelectedIndex(-1);
        jComboBStatus.setBorder(null);
        jComboBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBStatusActionPerformed(evt);
            }
        });

        jLNome.setBackground(new java.awt.Color(30, 30, 30));
        jLNome.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLNome.setForeground(java.awt.Color.gray);
        jLNome.setText("Nome");

        jTPIncscricaoEstadual.setBackground(new java.awt.Color(229, 229, 229));
        jTPIncscricaoEstadual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPIncscricaoEstadual.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPIncscricaoEstadual.setForeground(new java.awt.Color(0, 0, 0));

        jLInscricaoEstadual.setBackground(new java.awt.Color(30, 30, 30));
        jLInscricaoEstadual.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLInscricaoEstadual.setForeground(java.awt.Color.gray);
        jLInscricaoEstadual.setText("Inscrição Estadual");

        jTPCNPJ.setBackground(new java.awt.Color(229, 229, 229));
        jTPCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPCNPJ.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPCNPJ.setForeground(new java.awt.Color(0, 0, 0));

        jLRazaoSocial.setBackground(new java.awt.Color(30, 30, 30));
        jLRazaoSocial.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLRazaoSocial.setForeground(java.awt.Color.gray);
        jLRazaoSocial.setText("Razão Social");

        jTPRazaoSocial.setBackground(new java.awt.Color(229, 229, 229));
        jTPRazaoSocial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPRazaoSocial.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPRazaoSocial.setForeground(new java.awt.Color(0, 0, 0));

        jLFone1.setBackground(new java.awt.Color(30, 30, 30));
        jLFone1.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLFone1.setForeground(java.awt.Color.gray);
        jLFone1.setText("Fone 1");

        jFTFFone1.setBackground(new java.awt.Color(229, 229, 229));
        jFTFFone1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jFTFFone1.setForeground(java.awt.Color.gray);
        try {
            jFTFFone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFFone1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTFFone1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        jLEmail.setBackground(new java.awt.Color(30, 30, 30));
        jLEmail.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLEmail.setForeground(java.awt.Color.gray);
        jLEmail.setText("E-mail");

        jTPEmail.setBackground(new java.awt.Color(229, 229, 229));
        jTPEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPEmail.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPEmail.setForeground(new java.awt.Color(0, 0, 0));

        jLFone2.setBackground(new java.awt.Color(30, 30, 30));
        jLFone2.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLFone2.setForeground(java.awt.Color.gray);
        jLFone2.setText("Fone 2");

        jFTFFone2.setBackground(new java.awt.Color(229, 229, 229));
        jFTFFone2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jFTFFone2.setForeground(java.awt.Color.gray);
        try {
            jFTFFone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFFone2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTFFone2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        jLCep.setBackground(new java.awt.Color(30, 30, 30));
        jLCep.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLCep.setForeground(java.awt.Color.gray);
        jLCep.setText("CEP");

        jTPCep.setBackground(new java.awt.Color(229, 229, 229));
        jTPCep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPCep.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPCep.setForeground(new java.awt.Color(0, 0, 0));

        jButtonBuscarcep.setBackground(new java.awt.Color(229, 229, 229));
        jButtonBuscarcep.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jButtonBuscarcep.setForeground(java.awt.Color.gray);
        jButtonBuscarcep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-pesquisar-24.png"))); // NOI18N
        jButtonBuscarcep.setBorderPainted(false);
        jButtonBuscarcep.setHideActionText(true);
        jButtonBuscarcep.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonBuscarcep.setIconTextGap(30);
        jButtonBuscarcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarcepActionPerformed(evt);
            }
        });

        jButtonAddCEP.setBackground(new java.awt.Color(229, 229, 229));
        jButtonAddCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-soma-30.png"))); // NOI18N
        jButtonAddCEP.setBorderPainted(false);
        jButtonAddCEP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddCEP.setIconTextGap(0);
        jButtonAddCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCEPActionPerformed(evt);
            }
        });

        jLComplemento.setBackground(new java.awt.Color(30, 30, 30));
        jLComplemento.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLComplemento.setForeground(java.awt.Color.gray);
        jLComplemento.setText("Complemento");

        jTPComplemento.setBackground(new java.awt.Color(229, 229, 229));
        jTPComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPComplemento.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPComplemento.setForeground(new java.awt.Color(0, 0, 0));

        jLRua.setBackground(new java.awt.Color(30, 30, 30));
        jLRua.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLRua.setForeground(java.awt.Color.gray);
        jLRua.setText("Rua");

        jTPRua.setBackground(new java.awt.Color(229, 229, 229));
        jTPRua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPRua.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPRua.setForeground(new java.awt.Color(0, 0, 0));

        jLBairro.setBackground(new java.awt.Color(30, 30, 30));
        jLBairro.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLBairro.setForeground(java.awt.Color.gray);
        jLBairro.setText("Bairro");

        jTPBairro.setBackground(new java.awt.Color(229, 229, 229));
        jTPBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPBairro.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPBairro.setForeground(new java.awt.Color(0, 0, 0));

        jLCidade.setBackground(new java.awt.Color(30, 30, 30));
        jLCidade.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLCidade.setForeground(java.awt.Color.gray);
        jLCidade.setText("Cidade");

        jTPCidade.setBackground(new java.awt.Color(229, 229, 229));
        jTPCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPCidade.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPCidade.setForeground(new java.awt.Color(0, 0, 0));

        jLEstado.setBackground(new java.awt.Color(30, 30, 30));
        jLEstado.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLEstado.setForeground(java.awt.Color.gray);
        jLEstado.setText("Estado");

        jTPEstado.setBackground(new java.awt.Color(229, 229, 229));
        jTPEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPEstado.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPEstado.setForeground(new java.awt.Color(0, 0, 0));

        jTPName.setBackground(new java.awt.Color(229, 229, 229));
        jTPName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPName.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPName.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout midpaneLayout = new javax.swing.GroupLayout(midpane);
        midpane.setLayout(midpaneLayout);
        midpaneLayout.setHorizontalGroup(
            midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midpaneLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTPEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addComponent(jTPName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPIncscricaoEstadual, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(139, 139, 139)
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTFFone2)
                            .addComponent(jLRazaoSocial)
                            .addComponent(jTPRazaoSocial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midpaneLayout.createSequentialGroup()
                                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDataNascimento)
                                    .addComponent(jTPCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLStatus)
                                    .addComponent(jComboBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midpaneLayout.createSequentialGroup()
                                .addComponent(jLFone1)
                                .addGap(429, 429, 429))
                            .addComponent(jFTFFone1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jTPId, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLInscricaoEstadual)
                    .addComponent(jLNome)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jLEmail)
                        .addGap(623, 623, 623)
                        .addComponent(jLFone2))
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTPComplemento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(midpaneLayout.createSequentialGroup()
                                        .addComponent(jTPCep, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonBuscarcep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAddCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLCep)))
                            .addComponent(jLComplemento)
                            .addComponent(jLId))
                        .addGap(41, 41, 41)
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCidade)
                            .addComponent(jLRua)
                            .addComponent(jTPRua, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBairro)
                            .addComponent(jLEstado)
                            .addComponent(jTPEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        midpaneLayout.setVerticalGroup(
            midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midpaneLayout.createSequentialGroup()
                        .addComponent(jLId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midpaneLayout.createSequentialGroup()
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStatus)
                            .addComponent(jLDataNascimento))
                        .addGap(1, 1, 1)))
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTPCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jLRazaoSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jTPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLInscricaoEstadual))
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jTPRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFone1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPIncscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLEmail))
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLFone2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTPEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFFone2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jLCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscarcep, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jLRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTPRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addComponent(jLBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTPBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTPEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(midpaneLayout.createSequentialGroup()
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCidade)
                            .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLComplemento)
                                .addComponent(jLEstado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(midpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58))
        );

        bottompane.setBackground(new java.awt.Color(255, 255, 255));

        jButtonNew.setBackground(new java.awt.Color(51, 204, 255));
        jButtonNew.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonNew.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-adicionar-usuário-masculino-30.png"))); // NOI18N
        jButtonNew.setText("Novo");
        jButtonNew.setBorderPainted(false);
        jButtonNew.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonNew.setIconTextGap(40);
        jButtonNew.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(109, 217, 108));
        jButtonSave.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-verificar-arquivo-24.png"))); // NOI18N
        jButtonSave.setText("Salvar");
        jButtonSave.setBorderPainted(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonSave.setIconTextGap(40);
        jButtonSave.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(242, 159, 5));
        jButtonCancel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-cancelar-30.png"))); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonCancel.setIconTextGap(20);
        jButtonCancel.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonExclui.setBackground(new java.awt.Color(242, 48, 48));
        jButtonExclui.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonExclui.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-apagar-para-sempre-30.png"))); // NOI18N
        jButtonExclui.setText("Excluir");
        jButtonExclui.setBorderPainted(false);
        jButtonExclui.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonExclui.setIconTextGap(30);
        jButtonExclui.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottompaneLayout = new javax.swing.GroupLayout(bottompane);
        bottompane.setLayout(bottompaneLayout);
        bottompaneLayout.setHorizontalGroup(
            bottompaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottompaneLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonExclui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        bottompaneLayout.setVerticalGroup(
            bottompaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottompaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bottompaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExclui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jButtonSave.getAccessibleContext().setAccessibleName("jButtomNew");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottompane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(midpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(toppane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midpane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottompane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Cantina");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluiActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExitActionPerformed

    private void jButtonBuscarcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarcepActionPerformed

    private void jButtonAddCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddCEPActionPerformed

    private void jComboBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bottompane;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jButtonAddCEP;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarcep;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExclui;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBStatus;
    private javax.swing.JFormattedTextField jFTFFone1;
    private javax.swing.JFormattedTextField jFTFFone2;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLDataNascimento;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFone1;
    private javax.swing.JLabel jLFone2;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLInscricaoEstadual;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLRazaoSocial;
    private javax.swing.JLabel jLRua;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextPane jTPBairro;
    private javax.swing.JTextPane jTPCNPJ;
    private javax.swing.JTextPane jTPCep;
    private javax.swing.JTextPane jTPCidade;
    private javax.swing.JTextPane jTPComplemento;
    private javax.swing.JTextPane jTPEmail;
    private javax.swing.JTextPane jTPEstado;
    private javax.swing.JTextPane jTPId;
    private javax.swing.JTextPane jTPIncscricaoEstadual;
    private javax.swing.JTextPane jTPName;
    private javax.swing.JTextPane jTPRazaoSocial;
    private javax.swing.JTextPane jTPRua;
    private javax.swing.JPanel midpane;
    private javax.swing.JPanel toppane;
    // End of variables declaration//GEN-END:variables
}
