/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gabri
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TestejFrame
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        toppane = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jLId = new javax.swing.JLabel();
        jTPId = new javax.swing.JTextPane();
        jButtonBuscar = new javax.swing.JButton();
        jLDataNascimento = new javax.swing.JLabel();
        jTPDataNascimento = new javax.swing.JTextPane();
        jLStatus = new javax.swing.JLabel();
        jComboBStatus = new javax.swing.JComboBox<>();
        jLNome = new javax.swing.JLabel();
        jTPName = new javax.swing.JTextPane();
        jLCPF = new javax.swing.JLabel();
        jTPCPF = new javax.swing.JTextPane();
        jLRg = new javax.swing.JLabel();
        jTPRg = new javax.swing.JTextPane();
        jLMatricula = new javax.swing.JLabel();
        jTPMatricula = new javax.swing.JTextPane();
        jLFone1 = new javax.swing.JLabel();
        jTPFone1 = new javax.swing.JTextPane();
        jLEmail = new javax.swing.JLabel();
        jTPEmail = new javax.swing.JTextPane();
        jLFone2 = new javax.swing.JLabel();
        jTPFone2 = new javax.swing.JTextPane();
        jLCep = new javax.swing.JLabel();
        jTPCep = new javax.swing.JTextPane();
        jButtonBuscarcep = new javax.swing.JButton();
        jButtonAddCEP = new javax.swing.JButton();
        jLComplemento = new javax.swing.JLabel();
        jTPComplemento = new javax.swing.JTextPane();
        jLRua = new javax.swing.JLabel();
        jTPRua = new javax.swing.JTextPane();
        jLBairro = new javax.swing.JLabel();
        jTPBairro = new javax.swing.JTextPane();
        jTPEstado = new javax.swing.JTextPane();
        jLEstado = new javax.swing.JLabel();
        bottompane = new javax.swing.JPanel();
        jButtonNew = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonExclui = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fomulário de Teste da GABISZOKA");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1280, 832));
        setName("cadastro"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 832));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 832));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        toppane.setBackground(new java.awt.Color(109, 217, 108));
        toppane.setPreferredSize(new java.awt.Dimension(1280, 99));

        jLTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(242, 241, 243));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Cadastro Cliente");
        jLTitulo.setToolTipText("");
        jLTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBExit.setBackground(new java.awt.Color(109, 217, 108));
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-voltar-48.png"))); // NOI18N
        jBExit.setBorderPainted(false);
        jBExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppaneLayout = new javax.swing.GroupLayout(toppane);
        toppane.setLayout(toppaneLayout);
        toppaneLayout.setHorizontalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppaneLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403)
                .addComponent(jLTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppaneLayout.setVerticalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitulo)
                    .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLId.setBackground(new java.awt.Color(30, 30, 30));
        jLId.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLId.setForeground(java.awt.Color.gray);
        jLId.setText("ID");

        jTPId.setBackground(new java.awt.Color(229, 229, 229));
        jTPId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPId.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPId.setForeground(new java.awt.Color(0, 0, 0));

        jButtonBuscar.setBackground(new java.awt.Color(229, 229, 229));
        jButtonBuscar.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jButtonBuscar.setForeground(java.awt.Color.gray);
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-pesquisar-24.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setHideActionText(true);
        jButtonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonBuscar.setIconTextGap(30);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLDataNascimento.setBackground(new java.awt.Color(30, 30, 30));
        jLDataNascimento.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLDataNascimento.setForeground(java.awt.Color.gray);
        jLDataNascimento.setText("Data Nascimento");

        jTPDataNascimento.setBackground(new java.awt.Color(229, 229, 229));
        jTPDataNascimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPDataNascimento.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPDataNascimento.setForeground(new java.awt.Color(0, 0, 0));

        jLStatus.setBackground(new java.awt.Color(30, 30, 30));
        jLStatus.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLStatus.setForeground(java.awt.Color.gray);
        jLStatus.setText("Status");

        jComboBStatus.setBackground(new java.awt.Color(229, 229, 229));
        jComboBStatus.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jComboBStatus.setForeground(java.awt.Color.gray);
        jComboBStatus.setMaximumRowCount(2);
        jComboBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jComboBStatus.setSelectedIndex(-1);
        jComboBStatus.setBorder(null);
        jComboBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBStatusActionPerformed(evt);
            }
        });

        jLNome.setBackground(new java.awt.Color(30, 30, 30));
        jLNome.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLNome.setForeground(java.awt.Color.gray);
        jLNome.setText("Nome");

        jTPName.setBackground(new java.awt.Color(229, 229, 229));
        jTPName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPName.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPName.setForeground(new java.awt.Color(0, 0, 0));
        jTPName.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTPNameComponentAdded(evt);
            }
        });

        jLCPF.setBackground(new java.awt.Color(30, 30, 30));
        jLCPF.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLCPF.setForeground(java.awt.Color.gray);
        jLCPF.setText("CPF");

        jTPCPF.setBackground(new java.awt.Color(229, 229, 229));
        jTPCPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPCPF.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPCPF.setForeground(new java.awt.Color(0, 0, 0));

        jLRg.setBackground(new java.awt.Color(30, 30, 30));
        jLRg.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLRg.setForeground(java.awt.Color.gray);
        jLRg.setText("RG");

        jTPRg.setBackground(new java.awt.Color(229, 229, 229));
        jTPRg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPRg.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPRg.setForeground(new java.awt.Color(0, 0, 0));

        jLMatricula.setBackground(new java.awt.Color(30, 30, 30));
        jLMatricula.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLMatricula.setForeground(java.awt.Color.gray);
        jLMatricula.setText("Matrícula");

        jTPMatricula.setBackground(new java.awt.Color(229, 229, 229));
        jTPMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPMatricula.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPMatricula.setForeground(new java.awt.Color(0, 0, 0));

        jLFone1.setBackground(new java.awt.Color(30, 30, 30));
        jLFone1.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLFone1.setForeground(java.awt.Color.gray);
        jLFone1.setText("Fone 1");

        jTPFone1.setBackground(new java.awt.Color(229, 229, 229));
        jTPFone1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPFone1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPFone1.setForeground(new java.awt.Color(0, 0, 0));

        jLEmail.setBackground(new java.awt.Color(30, 30, 30));
        jLEmail.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLEmail.setForeground(java.awt.Color.gray);
        jLEmail.setText("E-mail");

        jTPEmail.setBackground(new java.awt.Color(229, 229, 229));
        jTPEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPEmail.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPEmail.setForeground(new java.awt.Color(0, 0, 0));

        jLFone2.setBackground(new java.awt.Color(30, 30, 30));
        jLFone2.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLFone2.setForeground(java.awt.Color.gray);
        jLFone2.setText("Fone 2");

        jTPFone2.setBackground(new java.awt.Color(229, 229, 229));
        jTPFone2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPFone2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPFone2.setForeground(new java.awt.Color(0, 0, 0));

        jLCep.setBackground(new java.awt.Color(30, 30, 30));
        jLCep.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLCep.setForeground(java.awt.Color.gray);
        jLCep.setText("CEP");

        jTPCep.setBackground(new java.awt.Color(229, 229, 229));
        jTPCep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPCep.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPCep.setForeground(new java.awt.Color(0, 0, 0));

        jButtonBuscarcep.setBackground(new java.awt.Color(229, 229, 229));
        jButtonBuscarcep.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jButtonBuscarcep.setForeground(java.awt.Color.gray);
        jButtonBuscarcep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-pesquisar-24.png"))); // NOI18N
        jButtonBuscarcep.setText("Buscar CEP");
        jButtonBuscarcep.setBorderPainted(false);
        jButtonBuscarcep.setHideActionText(true);
        jButtonBuscarcep.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonBuscarcep.setIconTextGap(30);
        jButtonBuscarcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarcepActionPerformed(evt);
            }
        });

        jButtonAddCEP.setBackground(new java.awt.Color(229, 229, 229));
        jButtonAddCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-soma-30.png"))); // NOI18N
        jButtonAddCEP.setBorderPainted(false);
        jButtonAddCEP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddCEP.setIconTextGap(0);
        jButtonAddCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCEPActionPerformed(evt);
            }
        });

        jLComplemento.setBackground(new java.awt.Color(30, 30, 30));
        jLComplemento.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLComplemento.setForeground(java.awt.Color.gray);
        jLComplemento.setText("Complemento");

        jTPComplemento.setBackground(new java.awt.Color(229, 229, 229));
        jTPComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPComplemento.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPComplemento.setForeground(new java.awt.Color(0, 0, 0));

        jLRua.setBackground(new java.awt.Color(30, 30, 30));
        jLRua.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLRua.setForeground(java.awt.Color.gray);
        jLRua.setText("Rua");

        jTPRua.setBackground(new java.awt.Color(229, 229, 229));
        jTPRua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPRua.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPRua.setForeground(new java.awt.Color(0, 0, 0));

        jLBairro.setBackground(new java.awt.Color(30, 30, 30));
        jLBairro.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLBairro.setForeground(java.awt.Color.gray);
        jLBairro.setText("Bairro");

        jTPBairro.setBackground(new java.awt.Color(229, 229, 229));
        jTPBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPBairro.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPBairro.setForeground(new java.awt.Color(0, 0, 0));

        jTPEstado.setBackground(new java.awt.Color(229, 229, 229));
        jTPEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 10, true));
        jTPEstado.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTPEstado.setForeground(new java.awt.Color(0, 0, 0));

        jLEstado.setBackground(new java.awt.Color(30, 30, 30));
        jLEstado.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLEstado.setForeground(java.awt.Color.gray);
        jLEstado.setText("Estado");

        bottompane.setBackground(new java.awt.Color(255, 255, 255));

        jButtonNew.setBackground(new java.awt.Color(166, 220, 232));
        jButtonNew.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonNew.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-adicionar-usuário-masculino-30.png"))); // NOI18N
        jButtonNew.setText("Novo");
        jButtonNew.setBorderPainted(false);
        jButtonNew.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonNew.setIconTextGap(40);
        jButtonNew.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(109, 217, 108));
        jButtonSave.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-verificar-arquivo-24.png"))); // NOI18N
        jButtonSave.setText("Salvar");
        jButtonSave.setBorderPainted(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonSave.setIconTextGap(40);
        jButtonSave.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(242, 159, 5));
        jButtonCancel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-cancelar-30.png"))); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonCancel.setIconTextGap(20);
        jButtonCancel.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonExclui.setBackground(new java.awt.Color(242, 48, 48));
        jButtonExclui.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButtonExclui.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/icons8-apagar-para-sempre-30.png"))); // NOI18N
        jButtonExclui.setText("Excluir");
        jButtonExclui.setBorderPainted(false);
        jButtonExclui.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonExclui.setIconTextGap(30);
        jButtonExclui.setPreferredSize(new java.awt.Dimension(200, 90));
        jButtonExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottompaneLayout = new javax.swing.GroupLayout(bottompane);
        bottompane.setLayout(bottompaneLayout);
        bottompaneLayout.setHorizontalGroup(
            bottompaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottompaneLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonExclui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottompaneLayout.setVerticalGroup(
            bottompaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottompaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottompaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExclui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jButtonSave.getAccessibleContext().setAccessibleName("jButtomNew");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottompane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTPName)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLId)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jTPId, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLNome)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTPCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLCPF))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLRg)
                                        .addComponent(jTPRg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTPEmail)
                                .addComponent(jLEmail)
                                .addComponent(jLCep))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jTPCep, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarcep, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLComplemento)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTPComplemento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTPFone2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLFone2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLDataNascimento)
                                                .addComponent(jTPDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(63, 63, 63)
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLStatus)))
                                        .addComponent(jTPMatricula)
                                        .addComponent(jTPFone1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLFone1, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPRua, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLRua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLBairro))
                        .addGap(39, 39, 39)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEstado)
                            .addComponent(jTPEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLBairro))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(toppane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLId)
                            .addComponent(jLDataNascimento)
                            .addComponent(jLStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome)
                            .addComponent(jLMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRg)
                            .addComponent(jLCPF)
                            .addComponent(jLFone1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTPRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLFone2)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(jLEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCep)
                            .addComponent(jLComplemento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonAddCEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTPCep)
                                .addComponent(jButtonBuscarcep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTPComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLEstado))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLRua)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPRua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bottompane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Cantina");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluiActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExitActionPerformed

    private void jComboBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBStatusActionPerformed

    private void jTPNameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTPNameComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPNameComponentAdded

    private void jButtonAddCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddCEPActionPerformed

    private void jButtonBuscarcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarcepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bottompane;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jButtonAddCEP;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarcep;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExclui;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBStatus;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLDataNascimento;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFone1;
    private javax.swing.JLabel jLFone2;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLRg;
    private javax.swing.JLabel jLRua;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextPane jTPBairro;
    private javax.swing.JTextPane jTPCPF;
    private javax.swing.JTextPane jTPCep;
    private javax.swing.JTextPane jTPComplemento;
    private javax.swing.JTextPane jTPDataNascimento;
    private javax.swing.JTextPane jTPEmail;
    private javax.swing.JTextPane jTPEstado;
    private javax.swing.JTextPane jTPFone1;
    private javax.swing.JTextPane jTPFone2;
    private javax.swing.JTextPane jTPId;
    private javax.swing.JTextPane jTPMatricula;
    private javax.swing.JTextPane jTPName;
    private javax.swing.JTextPane jTPRg;
    private javax.swing.JTextPane jTPRua;
    private javax.swing.JPanel toppane;
    // End of variables declaration//GEN-END:variables
}
