/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author aluno
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        id = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        cliente = new javax.swing.JLabel();
        inputCliente = new javax.swing.JComboBox<>();
        serviço = new javax.swing.JLabel();
        inputServico = new javax.swing.JComboBox<>();
        valor = new javax.swing.JLabel();
        inputValor = new javax.swing.JTextField();
        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        inputData = new javax.swing.JTextField();
        inputHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Observacao = new javax.swing.JLabel();
        agendar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Thiago", "Curativo", "150,00", "13/03/2023", "16:00"},
                {"2", "Simone", "Consulta", "250,00", "13/03/2023", "16:30"},
                {"3", "Ana", "Consulta", "250,00", "13/03/2023", "17:30"},
                {"4", "Caio", "Curativo", "150,00", "13/03/2023", "18:30"}
            },
            new String [] {
                "ID", "Nome", "Serviço", "Valor", "Data", "Hora"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 510, 100));

        id.setText("ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        inputId.setText("1");
        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });
        getContentPane().add(inputId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 30, -1));

        cliente.setText("Cliente");
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        inputCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiago", "Simone", "Ana", "Caio" }));
        inputCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClienteActionPerformed(evt);
            }
        });
        getContentPane().add(inputCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 200, -1));

        serviço.setText("Serviço");
        getContentPane().add(serviço, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        inputServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curativo", "Atendimento" }));
        getContentPane().add(inputServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, -1));

        valor.setText("Valor");
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        inputValor.setText("150,00");
        getContentPane().add(inputValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, -1));

        data.setText("Data");
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        hora.setText("Hora");
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        inputData.setText("21/12/21");
        inputData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataActionPerformed(evt);
            }
        });
        getContentPane().add(inputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, -1));

        inputHora.setText("15:00");
        getContentPane().add(inputHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 270, 130));

        Observacao.setText("Observação");
        getContentPane().add(Observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        agendar.setForeground(new java.awt.Color(255, 51, 51));
        agendar.setText("Agendar");
        getContentPane().add(agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputClienteActionPerformed

    private void inputDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Observacao;
    private javax.swing.JButton agendar;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel data;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox<String> inputCliente;
    private javax.swing.JTextField inputData;
    private javax.swing.JTextField inputHora;
    private javax.swing.JTextField inputId;
    private javax.swing.JComboBox<String> inputServico;
    private javax.swing.JTextField inputValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel serviço;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
